name: analisador_lexico
description: Analisador Léxico

homepage:
publish_to: none
version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  path: 1.8.2

dev_dependencies:
  analyzer: 4.1.0
  equatable: 2.0.3
  dartz: 0.10.1

scripts:
  run: dart src/main.dart
